//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointsConsumeWebService.getpointswebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Get Points Web ServiceSoap", Namespace="http://getpointswebservice.org/", ConfigurationName="getpointswebservice.GetPointsWebServiceSoap")]
    public interface GetPointsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name studentNumber from namespace http://getpointswebservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://getpointswebservice.org/GetPoints", ReplyAction="*")]
        PointsConsumeWebService.getpointswebservice.GetPointsResponse GetPoints(PointsConsumeWebService.getpointswebservice.GetPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://getpointswebservice.org/GetPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsConsumeWebService.getpointswebservice.GetPointsResponse> GetPointsAsync(PointsConsumeWebService.getpointswebservice.GetPointsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPoints", Namespace="http://getpointswebservice.org/", Order=0)]
        public PointsConsumeWebService.getpointswebservice.GetPointsRequestBody Body;
        
        public GetPointsRequest() {
        }
        
        public GetPointsRequest(PointsConsumeWebService.getpointswebservice.GetPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://getpointswebservice.org/")]
    public partial class GetPointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string studentNumber;
        
        public GetPointsRequestBody() {
        }
        
        public GetPointsRequestBody(string studentNumber) {
            this.studentNumber = studentNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPointsResponse", Namespace="http://getpointswebservice.org/", Order=0)]
        public PointsConsumeWebService.getpointswebservice.GetPointsResponseBody Body;
        
        public GetPointsResponse() {
        }
        
        public GetPointsResponse(PointsConsumeWebService.getpointswebservice.GetPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://getpointswebservice.org/")]
    public partial class GetPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPointsResult;
        
        public GetPointsResponseBody() {
        }
        
        public GetPointsResponseBody(int GetPointsResult) {
            this.GetPointsResult = GetPointsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetPointsWebServiceSoapChannel : PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPointsWebServiceSoapClient : System.ServiceModel.ClientBase<PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap>, PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap {
        
        public GetPointsWebServiceSoapClient() {
        }
        
        public GetPointsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetPointsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPointsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPointsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsConsumeWebService.getpointswebservice.GetPointsResponse PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap.GetPoints(PointsConsumeWebService.getpointswebservice.GetPointsRequest request) {
            return base.Channel.GetPoints(request);
        }
        
        public int GetPoints(string studentNumber) {
            PointsConsumeWebService.getpointswebservice.GetPointsRequest inValue = new PointsConsumeWebService.getpointswebservice.GetPointsRequest();
            inValue.Body = new PointsConsumeWebService.getpointswebservice.GetPointsRequestBody();
            inValue.Body.studentNumber = studentNumber;
            PointsConsumeWebService.getpointswebservice.GetPointsResponse retVal = ((PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap)(this)).GetPoints(inValue);
            return retVal.Body.GetPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsConsumeWebService.getpointswebservice.GetPointsResponse> PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap.GetPointsAsync(PointsConsumeWebService.getpointswebservice.GetPointsRequest request) {
            return base.Channel.GetPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsConsumeWebService.getpointswebservice.GetPointsResponse> GetPointsAsync(string studentNumber) {
            PointsConsumeWebService.getpointswebservice.GetPointsRequest inValue = new PointsConsumeWebService.getpointswebservice.GetPointsRequest();
            inValue.Body = new PointsConsumeWebService.getpointswebservice.GetPointsRequestBody();
            inValue.Body.studentNumber = studentNumber;
            return ((PointsConsumeWebService.getpointswebservice.GetPointsWebServiceSoap)(this)).GetPointsAsync(inValue);
        }
    }
}
